scrape_configs:
  - job_name: 'springboot'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.120.83:8080']
  - job_name: 'vertx3x'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.120.83:8082']
  - job_name: 'vertx4x'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.120.83:8084']